parameters:
    jaitec_alias:
        0: VaRCScev0fNjk9HDGlmTobPq7rIsYtux5yzAgBE4pFihUJnK3LMd&O1Q6XZ
        1: JK3LMN&tuvx5yzABCDE4FGHIOP1QRSTUV6XYZabcde0fghijk9lmnopq7rs
        2: STUV6XYZabcde0fghijk9lmK3LMNnopq7rstuv&OP1QRx5yzABCDE4FGHIJ
        3: OP1QRk9lmnopq7rsSTdzABCDEuJK3LMN4FGHe0fghijt&vx5yUV6XYZabcI
    